// CPU/NPU cooperative smoke test using a real YOLOv8n INT8 weight block.
// Data is generated by tools/gen_yolo_pwconv_real_smoke.py.

#include "firmware.h"
#include "yolo_ops.h"
#include "yolo_pwconv_real_data.h"
#include <stdint.h>

#define ACT_DDR 0x40030000u
#define WGT_DDR 0x40032000u
#define OUT_DDR 0x40034000u

#define ACT_BASE 0u
#define WGT_BASE 0u
#define OUT_BASE 0u

static void write_ddr_word128(uint32_t byte_addr, uint32_t word_idx, const uint32_t lanes[4])
{
    volatile uint32_t *ptr = (volatile uint32_t *)(byte_addr + word_idx * 16u);
    ptr[0] = lanes[0];
    ptr[1] = lanes[1];
    ptr[2] = lanes[2];
    ptr[3] = lanes[3];
}

static uint32_t read_ddr_byte(uint32_t byte_addr, uint32_t word_idx, uint32_t byte_idx)
{
    volatile uint32_t *ptr = (volatile uint32_t *)(byte_addr + word_idx * 16u);
    uint32_t lane = ptr[byte_idx >> 2];
    return (lane >> ((byte_idx & 3u) * 8u)) & 0xFFu;
}

void usercode7(void)
{
    uint32_t i;
    uint32_t pos;
    uint32_t oc;
    uint32_t errors = 0u;

    print_str("YOLO REAL PWCONV CPU SMOKE\n");

    for (i = 0u; i < YOLO_REAL_PW_ACT_WORDS; i++)
        write_ddr_word128(ACT_DDR, i, yolo_real_pw_act_words[i]);
    for (i = 0u; i < YOLO_REAL_PW_WGT_WORDS; i++)
        write_ddr_word128(WGT_DDR, i, yolo_real_pw_wgt_words[i]);
    for (i = 0u; i < YOLO_REAL_PW_OUT_WORDS; i++) {
        const uint32_t zero[4] = {0u, 0u, 0u, 0u};
        write_ddr_word128(OUT_DDR, i, zero);
    }

    if (!yolo_dma_ddr_to_act(ACT_DDR, ACT_BASE, YOLO_REAL_PW_ACT_WORDS)) {
        print_str("  act DMA timeout\n");
        errors++;
    }
    if (errors == 0u &&
        !yolo_dma_ddr_to_wgt(WGT_DDR, WGT_BASE, YOLO_REAL_PW_WGT_WORDS)) {
        print_str("  wgt DMA timeout\n");
        errors++;
    }
    if (errors == 0u &&
        !yolo_run_pw_conv1x1(ACT_BASE, WGT_BASE, OUT_BASE,
                             YOLO_REAL_PW_IN_W, YOLO_REAL_PW_IN_H,
                             YOLO_REAL_PW_IC, YOLO_REAL_PW_OC,
                             yolo_real_pw_bias,
                             YOLO_REAL_PW_SCALE_MUL,
                             YOLO_REAL_PW_SCALE_SHIFT,
                             NPU_CTRL_RELU_EN)) {
        print_str("  pwconv run timeout/error\n");
        errors++;
    }
    if (errors == 0u &&
        !yolo_dma_out_to_ddr(OUT_DDR, OUT_BASE, YOLO_REAL_PW_OUT_WORDS, 0u)) {
        print_str("  out DMA timeout\n");
        errors++;
    }

    for (pos = 0u; pos < YOLO_REAL_PW_OUT_WORDS; pos++) {
        for (oc = 0u; oc < YOLO_REAL_PW_OC; oc++) {
            uint32_t got = read_ddr_byte(OUT_DDR, pos, oc);
            uint32_t expect = yolo_real_pw_expected[pos][oc];
            if (got != expect) {
                errors++;
                print_str("  mismatch pos=");
                print_dec(pos);
                print_str(" oc=");
                print_dec(oc);
                print_str(" got=");
                print_dec(got);
                print_str(" exp=");
                print_dec(expect);
                print_str("\n");
            }
        }
    }

    if (errors == 0u) {
        print_str("YOLO REAL PWCONV CPU SMOKE PASS\n");
        return;
    }

    print_str("YOLO REAL PWCONV CPU SMOKE FAIL errors=");
    print_dec(errors);
    print_str("\n");
    __asm__ volatile ("ebreak");
}
